console.log('Hello Winc Academy');
        let name='Jeffrey';
        console.log('Jeffrey');
        let a=4+4;
        a=8;
        console.log(a);
        let b=2;
        let c=b+20;
        c=22;
        console.log(c);
        let d=100;
        let e=d-75;
        e=25;
        console.log(e);
        let f=10;
        let g=f*10;
        g=100;
        console.log(g);
        let i=1000;
        let j=i/4;
        j=250;
        console.log(j);
        let k=10;
        let l=k%100;
        l=10;
        console.log(l);
        let age=56;
        let number='zesenvijftig';